# Generated by Django 5.2.6 on 2025-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_age_user_allow_peer_matching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_assessment_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_community_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_crisis_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reduced_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='safety_plan_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='screen_reader',
            field=models.BooleanField(default=False),
        ),
    ]
