# Generated by Django 5.1.7 on 2025-10-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_notifications_user_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enable_assessment_reminders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enable_community_updates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enable_crisis_alerts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='high_contrast',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_visibility',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reduced_motion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='safety_plan_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='screen_reader',
        ),
    ]
