# Generated by Django 5.1.7 on 2025-10-24 13:15
# This migration is empty to resolve conflicts

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_email_notifications_and_more'),
    ]

    operations = [
        # Empty migration to resolve conflicts
        # Actual fields are added in 0005_add_user_approval_fields.py
    ]
