# Generated by Django 5.1.7 on 2025-10-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_user_approval_fields'),
    ]

    operations = [
    ]
