# Generated by Django 5.1.7 on 2025-10-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_approved_at_user_approved_by_user_is_approved_and_more'),
        ('accounts', '0006_merge_20251024_1523'),
    ]

    operations = [
    ]
