# Generated by Django 5.1.7 on 2025-10-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontact',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientcontact',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='client',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='guide',
        ),
        migrations.DeleteModel(
            name='ClientAssignment',
        ),
        migrations.DeleteModel(
            name='ClientContact',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
