# Generated by Django 5.1.7 on 2025-10-15 10:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('habit_building', 'Habit Building'), ('fitness', 'Fitness Goal'), ('mindfulness', 'Mindfulness Practice'), ('social', 'Social Connection'), ('learning', 'Personal Development'), ('creativity', 'Creative Expression')], max_length=20)),
                ('instructions', models.TextField()),
                ('target_days', models.PositiveIntegerField(default=7, help_text='Days per week to complete')),
                ('points_per_day', models.PositiveIntegerField(default=10)),
                ('bonus_points', models.PositiveIntegerField(default=50, help_text='Bonus for completing all days')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wellness_weekly_challenge',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MoodPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('weekly_trend', 'Weekly Trend'), ('trigger_analysis', 'Trigger Analysis'), ('improvement_suggestion', 'Improvement Suggestion'), ('streak_analysis', 'Streak Analysis')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('insights', models.JSONField(help_text='Detailed analysis data')),
                ('recommendations', models.JSONField(default=list, help_text='AI-generated recommendations')),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('analysis_period_start', models.DateField()),
                ('analysis_period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wellness_mood_pattern',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWeeklyChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_completed', models.PositiveIntegerField(default=0)),
                ('completion_dates', models.JSONField(default=list, help_text='List of dates when challenge was completed')),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.weeklychallenge')),
            ],
            options={
                'db_table': 'wellness_weekly_progress',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
