# Generated by Django 5.1.7 on 2025-10-09 14:22

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_merge_20241009_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='options',
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='question_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessmentresponse',
            name='response_time',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentresponse',
            name='response_value',
            field=models.IntegerField(),
        ),
    ]
