# Generated by Django 5.1.7 on 2025-10-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_update_assessment_type_for_custom_assessments'),
        ('assessments', '0005_remove_assessmentquestion_options_and_more'),
    ]

    operations = [
    ]
