# Generated by Django 5.1.7 on 2025-11-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocontent',
            name='duration_seconds',
            field=models.IntegerField(default=1, help_text='Audio duration in seconds'),
        ),
    ]
