# Generated by Django 5.1.7 on 2025-11-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_audiocontent_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocontent',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External audio URL', null=True),
        ),
        migrations.AlterField(
            model_name='audiocontent',
            name='duration_seconds',
            field=models.IntegerField(blank=True, default=1, help_text='Audio duration in seconds', null=True),
        ),
    ]
