# Generated by Django 5.1.7 on 2025-10-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_chatroom_options_and_more'),
        ('community', '0002_enhance_forum_comments'),
    ]

    operations = [
    ]
