# Generated by Django 5.1.7 on 2025-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_merge_20251016_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='max_participants',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
