# Generated by Django 5.1.7 on 2025-10-18 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_chatroom_max_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peersupportmatch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin or Guide who approved this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_support_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='availability',
            field=models.TextField(blank=True, help_text="User's availability schedule"),
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='contact_preference',
            field=models.CharField(choices=[('chat', 'Text Chat'), ('video', 'Video Call'), ('phone', 'Phone Call'), ('email', 'Email')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='description',
            field=models.TextField(default=99999, help_text='Detailed description of support needed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='previous_support',
            field=models.BooleanField(default=False, help_text='Has received peer support before'),
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='reason',
            field=models.CharField(default=0, help_text='Brief reason for support', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable'),
        ),
        migrations.AddField(
            model_name='peersupportmatch',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='peersupportmatch',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Admin/Guide Approval'), ('pending', 'Pending Match'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
    ]
